### ISSUE TITLE
Primary branch config is ignored

### ISSUE THREAD

**Issue by domenikk** [kislerdm/terraform-provider-neon#42] opened 2023-08-27 19:11 UTC
### Terraform Version
```
Terraform v1.5.6
on darwin_arm64
+ provider registry.terraform.io/kislerdm/neon v0.2.1
```
### Provider Version
```
0.2.1
```
### Affected Resource(s)
- neon_project

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    neon = {
      source  = "kislerdm/neon"
      version = "0.2.1"
    }
  }
}

provider "neon" {}

resource "neon_project" "this" {
  name      = var.project_name
  region_id = var.region

  branch {
    name = "master"
    database_name = "neon-test"
    role_name = "admin"
  }
}
```

### Debug Output
https://gist.github.com/domenikk/7eae89c13154375f721a800c00e6e363

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Primary branch should have been created using the values (`name`, `database_name`, `role_name`) provided in config.

### Actual Behavior
Branch has been created with the default values from Neon, ignoring config. From `.tfstate` file:
```json
"branch": [
  {
    "database_name": "neondb",
    "id": "br-frosty-cherry-96448510",
    "name": "main",
    "role_name": "neon.user"
  }
]
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by domenikk** [comment] 2023-08-27 19:38
@kislerdm This line stood out after a quick review of the relevant code: https://github.com/kislerdm/terraform-provider-neon/blob/e93ab5c15bbbb052b4b7f969cd8c69290c48d1bc/internal/provider/resource_project.go#L330 (`RoleName` instead of `DatabaseName`).
Not sure if it explains why branch `name` and `role_name` are ignored as well.

**Comment by kislerdm** [comment] 2023-09-16 13:13
@domenikk Hello! Thank you for opening the issue. Could you please clarify the desired behavior? Thanks!

**Comment by kislerdm** [comment] 2023-09-18 21:40
@domenikk hey! A headsup: the issue's root cause was identified, it will be fixed in v0.2.2. ETA: 2023-09-19.

**Comment by domenikk** [comment] 2023-09-19 06:18
@kislerdm that's great news. Thanks a lot for looking into it

**Comment by kislerdm** [comment] 2023-09-19 07:21
@domenikk Hey! Thank you for your contribution! May I kindly ask to star the repo to gain its visibility? Thanks!

**Closed** 2023-09-19 23:00 UTC
Labels: bug
