### ISSUE TITLE
default_endpoint_setting is ignored

### ISSUE THREAD

**Issue by kbumsik** [kislerdm/terraform-provider-neon#48] opened 2023-09-12 11:08 UTC
Hi there,

Thank you for opening an issue.

### Terraform Version
1.5.7

### Provider Version
0.2.1

### Affected Resource(s)
Please list the resources as a list, for example:
- neon_project
- 

### Terraform Configuration Files
```hcl
resource "neon_project" "this" {
  name = var.name
  # https://neon.tech/docs/introduction/regions
  region_id           = "aws-us-west-2"
  pg_version          = "15"
  compute_provisioner = "k8s-neonvm"

  history_retention_seconds = 604800 # 7 days
  branch {
    name = "main"
    database_name = "do_not_use_neondb_default"
    role_name = "root"
  }
  default_endpoint_settings {
    autoscaling_limit_min_cu = 0.25
    autoscaling_limit_max_cu = 2
    suspend_timeout_seconds = 300 # 5 min
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior

The default compute setting should be changed after creation, but it is ignored

### Actual Behavior

![Screenshot by Dropbox Capture](https://github.com/kislerdm/terraform-provider-neon/assets/7823583/a794acee-2fb8-4c2d-a668-b30dc9a5cf25)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know?

### References
This is somewhat similar to  #42

**Comment by kislerdm** [comment] 2023-09-16 13:20
@kbumsik Hey Bumsik! Thank you for opening the issue!

Have you tried to verify what happens when you create a new branch using terraform? I suspect that the default project settings may not be reflected in the UI when you create new branch there.

Thanks!
Dmitry

**Comment by kislerdm** [comment] 2023-09-18 21:41
@kbumsik Hey! The root cause was identified, the fix will be released in v0.2.2. ETA: 2023-09-20.

**Comment by kbumsik** [comment] 2023-09-19 01:51
Hi, I just saw your replies. That's great you already fixed it 👍 

I hope I could contribute this TF module directly someday.

**Comment by kislerdm** [comment] 2023-09-19 07:20
@kbumsik Hey Bumsik! Thank you for your feedback and look forward to further cooperation! 🙂 BTW may I kindly ask to start the repo for its visibility? Thanks!

**Comment by kbumsik** [comment] 2023-09-19 07:44
> start the repo for its visibility?

Do you mean making a fork?

**Comment by kislerdm** [comment] 2023-09-19 10:43
@kbumsik no, I mean pressing the "star button" for this repo 😉

![image](https://github.com/kislerdm/terraform-provider-neon/assets/13434797/a2ef68b4-8f99-4938-80eb-0607492ce0f2)

**Closed** 2023-09-19 23:00 UTC
Labels: bug

**Comment by kbumsik** [comment] 2023-09-20 01:15
Such typo 😉 Hope you get ♾️ stars some day!
