### ISSUE TITLE
Requested history retention seconds exceeds allowed maximum

### ISSUE THREAD

**Issue by dmiric** [kislerdm/terraform-provider-neon#104] opened 2024-07-20 19:56 UTC
Hi there,

Thank you for opening an issue.

### Terraform Version
1.9.2

### Provider Version
latest

### I get this error
╷
│ Error: [HTTP Code: 400][Error Code: ] requested history retention seconds exceeds allowed maximum; requested_history_retention_seconds:'\U00093a80', max:'\U00015180'
│ 
│   with neon_project.db,
│   on main.tf line 79, in resource "neon_project" "db":
│   79: resource "neon_project" "db" {
│ 
╵

According to documentation requested_history_retention_seconds dosen't exist.

I'm testing Neon on free account for now, maybe that could be the problem?

**Comment by kislerdm** [comment] 2024-09-16 17:53
@dmiric hello! Thanks for raising the issue! Could you please share the snippet of the terraform manifest execution of which led to the error? Thanks!

**Comment by dmiric** [comment] 2024-09-16 18:10
I don't have that code anymore, but if I remember it was just an example. I
think it has something to do with being on a free account, that's why I
added that remark.

**Comment by kislerdm** [comment] 2024-09-17 22:22
Sorry, but I cannot reproduce the issue without the tf manifest snippet, hence no further investigation could be conducted. Thanks for understanding! I'm closing the ticket, please feel free to reopen it shall the issue occur again.

**Closed** 2024-09-17 22:22 UTC
